project:
  type: website
  output-dir: docs

website:
  title: "Lexi Taylor's Website Warmup"
  site-path: "/warmup-lexi-taylor/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
      - href: blog/index.qmd
        text: Blog


  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Articles"
        contents:
          - index.qmd
          - articles/article_01.qmd
          - articles/article_02.qmd
          - articles/article_03.qmd
      - section: "Blog"
        contents:
          - index.qmd
          - blog/blog_01.qmd
          - blog/blog_02.qmd
          - blog/blog_03.qmd
          - blog/blog_04.qmd
          - blog/blog_05.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true