project:
  type: website
  output-dir: docs

website:
  title: "Lexi Taylor's Website"
  site-path: "/warmup-lexi-taylor/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 
      - href: posts/index.qmd
        text: Blog

  sidebar:

    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Articles"
          href: articles/index.qmd
          contents: 
            - text: "Minimum Function"
              href:  articles/article_01.qmd
            - text: "Recursion"
              href:  articles/article_02.qmd
            - text: " Minor Enhancement"
              href:  articles/article_03.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"
          sort:
            - "date desc"


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    footnotes-hover: true

execute:
  freeze: true



