project:
  type: website
  output-dir: docs

website:
  title: "Lexi Taylor's Website"
  site-path: "/warmup-lexi-taylor/"
  navbar:
    tools:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Articles
        menu:
          - href: articles/index.qmd
            text: "Articles" 
          - href: articles/article_01.qmd
            text: "Minimum Function"
          - href: articles/article_02.qmd
            text: "Recursion" 
          - href: articles/article_03.qmd
            text: "Major Enhancement"
      - text: Blog
        menu:
          - href: posts/index.qmd
            text: "Blog" 
          - href: posts/2023-11-11-college-work
            text: "Navigating the Transition from College to Work"
          - href: posts/2023-11-17-animals-happiness
            text: "The Benefits of Animals in Your Life" 
          - href: posts/2023-11-17-essay-modification
            text: "Essay Modification"
          - href: posts/2023-11-17-life-work
            text: "Finding Balance Between Life and Work"
          - href: posts/2023-11-17-minor-enhancement
            text: "Minor Enhancement"

  sidebar:

    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Articles"
          href: articles/index.qmd
          contents: 
            - text: "Minimum Function"
              href:  articles/article_01.qmd
            - text: "Recursion"
              href:  articles/article_02.qmd
            - text: "Major Enhancement"
              href:  articles/article_03.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"
          sort:
            - "date desc"


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    footnotes-hover: true

execute:
  freeze: true



